travis:
  secure:
    BINSTAR_TOKEN: tGG/fqLwgKEnxBnXYHwYCQv6mBAULFHVNmhwjQrhumZ1/P0QQxDhzzR25ExNFCi4uo31zPlqjDYhgdkxgO0Jf5wVJPYKs4zi6ZXReMFGiU5hGHhgyFXtET2/213JiP5e2hWKywPR1+c5/5YxGizpnq2FoBTMs5rWtIKMnbSObEVnQ6/hJTX0aR6RD/97udmgxl9suZst0ouf+P3R5YkCjv7IK80q/z9dHZtSTz7j1ofSzt3I2sCQhxdvdp0omjoJruxSstl/XFf+hx2m6Vud26oxK3T3QL+ad3zBtusgbJPL2ildtJbO8M6sVOPxi56NI6A6i6BTBj9ZZerjIe7xshbU2beKom2nYHFl/9XpkztuzNBQiXmyRHAHNXiYCfqhBBuZEIqpJltz+Ymx0wAQf8VEdfaPsnZ5y9JsbAv14X/3sJCpZrTTAcvn5Ux3Icq2Y2aGzaNDEVBkGom9yaUoag0zBRtEGEKT/iK/X99cwc/cmRPooubgOTlRUbANijd8/fwrEfRjm6vGOIMnSx2f2zbnFbIQFuLdv/cntMJBSPMyMZ+66CldnALS8c+sDPMDm49ldMphj++ZspdYwpsHBTSdMZMEcZZfMNDIihBXyxMxxky12IGzxyuDKZ02ko6fJndEZLJZ+sN3UT4MH0OCNPINsEkDN0kZCdtKnzppbcA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
